project:
  type: book
  output-dir: dist
  resources:
    - pdf/enrollment-notice.pdf
    - pdf/enrollment-notice-midterm.pdf
    - pdf/week1-exercises.pdf
    - pdf/week2-exercises.pdf
    - pdf/week3-exercises.pdf
    - pdf/week4-exercises.pdf
    - pdf/week5-exercises.pdf
    - pdf/week6-exercises.pdf
    - pdf/week7-exercises.pdf
    - pdf/week8-exercises.pdf
    - pdf/week8-line-integral-explanation.pdf
    - pdf/week9-exercises.pdf
    - pdf/week10-exercises.pdf
  render:
    - index.qmd
    - textbook-toc.qmd
    - position-time.qmd
    - velocity-acceleration.qmd
    - laws-and-concepts.qmd
    - equations-of-motion.qmd
    - oscillation-and-wave.qmd
    - central-force.qmd
    - coordinate-transformations.qmd
    - many-particle-and-rigid-body.qmd
    - week1-exercises.qmd
    - week2-exercises.qmd
    - week3-exercises.qmd
    - week4-exercises.qmd
    - week5-exercises.qmd
    - week6-exercises.qmd
    - week7-exercises.qmd
    - week8-exercises.qmd
    - week9-exercises.qmd
    - week10-exercises.qmd

book:
  title: "力学 I"
  author: "品岡寛"
  navbar:
    search: true
    right:
      - text: "演習 PDF"
        menu:
          - text: "第1週"
            href: pdf/week1-exercises.pdf
          - text: "第2週"
            href: pdf/week2-exercises.pdf
          - text: "第3週"
            href: pdf/week3-exercises.pdf
          - text: "第4週"
            href: pdf/week4-exercises.pdf
          - text: "第5週"
            href: pdf/week5-exercises.pdf
          - text: "第6週"
            href: pdf/week6-exercises.pdf
          - text: "第7週"
            href: pdf/week7-exercises.pdf
          - text: "第8週"
            href: pdf/week8-exercises.pdf
          - text: "第9週"
            href: pdf/week9-exercises.pdf
          - text: "第10週"
            href: pdf/week10-exercises.pdf
  chapters:
    - index.qmd
    - textbook-toc.qmd
    - position-time.qmd
    - velocity-acceleration.qmd
    - laws-and-concepts.qmd
    - equations-of-motion.qmd
    - oscillation-and-wave.qmd
    - central-force.qmd
    - coordinate-transformations.qmd
    - many-particle-and-rigid-body.qmd
    - week1-exercises.qmd
    - week2-exercises.qmd
    - week3-exercises.qmd
    - week4-exercises.qmd
    - week5-exercises.qmd
    - week6-exercises.qmd
    - week7-exercises.qmd
    - week8-exercises.qmd
    - week9-exercises.qmd
    - week10-exercises.qmd

format:
  html:
    theme: cosmo
    lang: ja
    toc: true
    code-copy: true
    code-overflow: wrap
    css: custom.css
    include-after-body: custom.js
