project:
  type: book
  output-dir: dist
  render:
    - index.qmd
    - position-time.qmd
    - velocity-acceleration.qmd
    - laws-and-concepts.qmd
    - week1-mock-questions.qmd
    - week2-mock-questions.qmd
    - week3-mock-questions.qmd
    - week4-mock-questions.qmd
    - week5-mock-questions.qmd
    - week6-mock-questions.qmd

book:
  title: "力学 I"
  author: "品岡寛"
  chapters:
    - index.qmd
    - position-time.qmd
    - velocity-acceleration.qmd
    - laws-and-concepts.qmd
    - week1-mock-questions.qmd
    - week2-mock-questions.qmd
    - week3-mock-questions.qmd
    - week4-mock-questions.qmd
    - week5-mock-questions.qmd
    - week6-mock-questions.qmd

format:
  html:
    theme: cosmo
    lang: ja
    toc: true
    code-copy: true
    code-overflow: wrap
    css: custom.css
    include-after-body: custom.js
